### ISSUE TITLE
Automatically unmount and remount on library change

### ISSUE THREAD

**Issue by Kaduo** [Abbotta4/beetfs-new#2]
Hello, this works great, thanks!

I was wondering if it was possible to add an option to have the filesystem be unmounted then remounted whenever the beets library is modified, so that it takes into account the changes.

I currently do this with the Hook plugin, but this may not be the most elegant solution...

```yaml
hook:
    hooks:
        - event: import
          command: screen -XS beet_mount quit && fusermount -u /path/to/mounted/fs && screen -dmS beet_mount beet mount /path/to/mounted/fs
```
